import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const poppins = Poppins({
  weight: '400'
})

export const metadata = {
  title: "Care Io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="max-w-480 mx-auto">
          <Navbar></Navbar>
          <div className="min-h-[calc(100vh-330px)]">
            {children}
          </div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
