import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import AuthProvider from "@/provider/AuthProvider";

const poppins = Poppins({
  weight: '400'
})

export const metadata = {
  title: "Care Io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-(--primary-color)/3`}>
        <div>
          <AuthProvider>
            {children}
          </AuthProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
